language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django==1.9.7 --use-mirrors"
  - DJANGO="django==1.8.13 --use-mirrors"
  - DJANGO="django==1.7.11 --use-mirrors"
  - DJANGO="django==1.6.11 --use-mirrors"
  - DJANGO="django==1.5.12 --use-mirrors"
  - DJANGO="django==1.4.22 --use-mirrors"

notifications:
  email: false

install:
  - pip install -r .travis-requirements.txt
  - pip install $DJANGO

script:
  - python django_lare/runtests/runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.10 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.4.10 --use-mirrors"
    - python: "3.4"
      env: DJANGO="django==1.4.10 --use-mirrors"
    - python: "3.5"
      env: DJANGO="django==1.4.10 --use-mirrors"
