language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION='>=1.4,<1.5'
  - DJANGO_VERSION='>=1.5,<1.6'
  - DJANGO_VERSION='>=1.6,<1.7'
  - DJANGO_VERSION='>=1.7,<1.8'
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.10'

notifications:
  email: false

install:
  - pip install -r .travis-requirements.txt
  - pip install Django$DJANGO_VERSION

script:
  - python django_lare/runtests/runtests.py

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION='>=1.7,<1.8'
    - python: "2.6"
      env: DJANGO_VERSION='>=1.8,<1.9'
    - python: "2.6"
      env: DJANGO_VERSION='>=1.9,<1.10'
    - python: "3.2"
      env: DJANGO_VERSION='>=1.4,<1.5'
    - python: "3.2"
      env: DJANGO_VERSION='>=1.9,<1.10'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.4,<1.5'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.9,<1.10'
    - python: "3.4"
      env: DJANGO_VERSION='>=1.4,<1.5'
    - python: "3.5"
      env: DJANGO_VERSION='>=1.4,<1.5'
    - python: "3.5"
      env: DJANGO_VERSION='>=1.5,<1.6'
    - python: "3.5"
      env: DJANGO_VERSION='>=1.6,<1.7'
    - python: "3.5"
      env: DJANGO_VERSION='>=1.7,<1.8'

